{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Book reader API docs",
    "description": "",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://api-br.herokuapp.com/api/" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Регистрация и Авторизация"
    },
    {
      "name": "Library",
      "description": "Библиотека всех книг"
    },
    {
      "name": "Training",
      "description": "Планирование тренировки"
    }
  ],
  "paths": {
    "/google":{
      "get": {
        "tags": ["Auth"],
        "summary": "User google auth",
        "parameters": [],
        "description": "необходимо создать роут /google-auth для получения имени и токена `${FRONTEND_URL}/google-auth?token=${token}&name=${name}`.",
        "responses": {
          "content": {
            "application/string":"token"
              }
            }
            }
    },
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authorization",
        "parameters": [],
        "requestBody": {
          "description": "Authorization's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthorizationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthorizationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/auth/logout": {
      "get": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {
              "application/json": {
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/library": {
      "get": {
        "tags": ["Library"],
        "summary": "Get all user books",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LibraryResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/library/addbook": {
      "post": {
        "tags": ["Library"],
        "summary": "Add book to plan",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Add book to plan",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddBookRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddBookResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/library/addReview": {
      "post": {
        "tags": ["Library"],
        "summary": "leave your rating and feedback",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "leave your rating and feedback",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddReviewRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddReviewResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/training": {
      "get": {
        "tags": ["Training"],
        "summary": "Get all user training",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrainingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/training/addTraining": {
      "post": {
        "tags": ["Training"],
        "summary": "Add book to plan",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Add book to plan",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddTrainingRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddTrainingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    },
    "/training/addResult": {
      "post": {
        "tags": ["Training"],
        "summary": "Add book to plan",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Add book to plan",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddResultRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AddResultResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Ivan"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "RegistrationResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            }
          }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
              "message": "Register user successful",
              "newUser": {
                "name": "Ivan",
                "email": "user@example.com"
              }
            }
          }
        ]
      },
      "AuthorizationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "AuthorizationResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "userId": {
              "type": "number",
              "description": "User's id",
              "example": "32143232436545474"
            }
          }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
              "userName": "Ivan",
              "token": "token",
              "message": "Вот твой токен! Пользуйся аккуратно!"
            }

          }
        ]
      },
      "LibraryResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
              "books": [
                {
                  "bookTitle": "Собор без крестов",
                  "author": "Шарапов",
                  "publicDate": "2003-12-02T22:00:00.000Z",
                  "numbOfPages": 560,
                  "readStatus": "Going to read",
                  "__v": 0
                }
              ]
            }
          }
        ]
      },
      "AddBookRequest": {
        "type": "object",
        "required": ["bookTitle", "author", "publicDate", "numbOfPages"],
        "properties": {
          "bookTitle": {
            "type": "string",
            "description": "Name of the book",
            "example": "Атлант расправил плечи"
          },
          "author": {
            "type": "string",
            "description": "Book author",
            "example": "Айн Рейд"
          },
          "publicDate": {
            "type": "date",
            "description": "Book publication date",
            "example": "2008-02-13"
          },
          "numbOfPages": {
            "type": "number",
            "description": "number of pages in a book",
            "example": 1070
          },
          "readStatus": {
            "type": "string",
            "description": "Going to read, Reading now, Already read",
            "example": "Going to read"
          }
        }
      },
      "AddBookResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          "bookTitle": {
            "type": "string",
            "description": "Name of the book",
            "example": "Атлант расправил плечи"
          },
          "author": {
            "type": "string",
            "description": "Book author",
            "example": "Айн Рейд"
          },
          "publicDate": {
            "type": "date",
            "description": "Book publication date",
            "example": "2008-02-13"
          },
          "numbOfPages": {
            "type": "number",
            "description": "number of pages in a book",
            "example": 1070
          },
          "readStatus": {
            "type": "string",
            "description": "Going to read, Reading now, Already read",
            "example": "Going to read"
          }
        }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
                "message": "Book added successfully",
                "result": {
                  "bookTitle": "Атлант расправил плечи",
                  "author": "Айн Рейд",
                  "publicDate": "12.02.2008",
                  "numbOfPages": 1070,
                  "readStatus": "Going to read"
                }
            }
        }
        ]
      },
      "AddReviewRequest": {
        "type": "object",
        "required": ["id", "rating"],
        "properties": {
          "id": {
            "type": "string",
            "description": "id",
            "example": "62068e4491030ccfd2ac5d06"
          },
          "rating": {
            "type": "number",
            "description": "rating",
            "example": 5
          },
          "comment": {
            "type": "string",
            "description": "comment",
            "example": "Отличная книга"
          }
        }
      },
      "AddReviewResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          "id": {
            "type": "string",
            "description": "id",
            "example": "62068e4491030ccfd2ac5d06"
          },
          "rating": {
            "type": "number",
            "description": "rating",
            "example": 5
          },
          "comment": {
            "type": "string",
            "description": "comment",
            "example": "Отличная книга"
          }
        }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
                "message": "Review added successful",
                "rating": 5,
                "comment": "Отличная книга"
            }
        }
        ]
      },
      "TrainingResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
              "trainingBooks": [
                {
                  "startTrain": "Собор без крестов"
                }
              ]
            }
          }
        ]
      },
      "AddTrainingRequest": {
        "type": "object",
        "required": ["endTrain", "trainingBooks", "booksTrain"],
        "properties": {
          "startTrain": {
            "type": "Date",
            "description": "начало тренировки",
            "example": "2022-02-13"
          },
          "endTrain": {
            "type": "Date",
            "description": "конец тренировки",
            "example": "2022-02-16"
          },
          "booksTrain": {
            "type": "Array",
            "description": "список книг",
            "example": "Собор без крестов"
          },
          "totalPages": {
            "type": "Number",
            "description": "общее количество страниц",
            "example": 1000
          },
          "owner": {
            "type": "Schema.Types.ObjectId"
        }
      }
      },
      "AddTrainingResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          "startTrain": {
            "type": "Date",
            "description": "начало тренировки",
            "example": "2022-02-13"
          },
          "endTrain": {
            "type": "Date",
            "description": "конец тренировки",
            "example": "2022-02-16"
          },
          "booksTrain": {
            "type": "Array",
            "description": "список книг",
            "example": "Собор без крестов"
          },
          "totalPages": {
            "type": "Number",
            "description": "общее количество страниц",
            "example": 1000
          },
          "owner": {
            "type": "Schema.Types.ObjectId"
        }
      }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "data": {
              "books": [
                {
                  "startTrain": "2022-02-13",
                  "endTrain": "2022-02-16",
                  "trainingBooks": 2,
                  "totalPages": 1000
                }
              ]
            }
          }
        ]
      },
      "AddResultRequest": {
        "type": "object",
        "required": ["endTrain", "trainingBooks", "booksTrain"],
        "properties": {
          "pagesResult": {
            "type": "Number",
            "description": "количество прочитанных страниц",
            "example": 10
          },
          "result": {
            "type": "Array",
            "description": "прочитанные книги",
            "example": "Собор без крестов"
          },
          "owner": {
            "type": "Schema.Types.ObjectId"
        }
      }
      },
      "AddResultResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
          "pagesResult": {
            "type": "Number",
            "description": "количество прочитанных страниц",
            "example": 10
          },
          "result": {
            "type": "Array",
            "description": "прочитанные книги",
            "example": "Собор без крестов"
          }
      }
        },
        "example": [
          {
            "status": "success",
            "code": 201,
            "message": "Ти молодчина, але потрібно швидше! Наступного разу тобі все вдасться)"
          }
        ]
      }
    }
  }, 
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
  }
}

